### ISSUE TITLE
Error en el formato de la tabla en el "Objetivo del curso"

### ISSUE THREAD

**Issue by pabloaguilar** [ComiteMexicanoDeInformatica/workshop#5]
En el tema este:
https://omegaup.com/course/Curso-OMI/assignment/COMI-intro#problems/COMI-Objetivo
La tabla al final no se muestra correctamente:
![image](https://user-images.githubusercontent.com/189223/67743456-ec5a3680-f9db-11e9-9143-faeec2ce8bbc.png)

**Comment by lhchavez** [comment]
https://github.com/ComiteMexicanoDeInformatica/Curso-OMI/pull/4 lo va a arreglar
