### ISSUE TITLE
Falta de ortografía

### ISSUE THREAD

**Issue by RodrigoLPA** [ComiteMexicanoDeInformatica/workshop#8]
Estructuras de Datos: Taquitos
doble "que" en la sección "Entrada" explicando caso 4.

**Comment by fjuarezgar** [comment]
Aquí: Si el entero es un 4, significa que que quieres saber el número de
tacos que has vendido hasta ahora.
Por lo demás me parece bastante claro. Si acaso esto:

Si el entero es un 1, significa que un nuevo cliente se forma en la fila,
por lo que deberás leer un entero t

Tal vez deba decir
Si el entero es un 1, significa que un nuevo cliente se forma en la fila,
por lo que, *enseguida*, deberás leer un entero t, el
número de tacos que pide.

Pero las instrucciones son claras.


Hasta luego. FJG

**Comment by frcepeda** [comment]
En efecto está mal la redacción. Dice
> Si el entero es un $4$, significa que **que** quieres saber el número de tacos que has vendido hasta ahora.
