### ISSUE TITLE
Error en caso

### ISSUE THREAD

**Issue by RodrigoLPA** [ComiteMexicanoDeInformatica/workshop#9]
Estructuras de datos Avanzadas: Mesa Redonda
En el caso 9.in solo hay un número en lugar de dos.

**Comment by fjuarezgar** [comment]
¿Estas revisando todos los problemas?
Hasta luego. FJG

**Comment by frcepeda** [comment]
Está completando el curso, y le pedí de favor que cuando viera algo mal abriera issue.

**Comment by fjuarezgar** [comment]
Lleva 2 buenas.
Hasta luego. FJG
